### PR TITLE
Brute Force + Best Approach + Comment

### PR DESCRIPTION
**Pull request by AkashYadavak**
I have written the brute force approach first, then best approach along with comments. So, it will help the beginner.
Thank you very much.

### CODE REVIEW

**Comment by shumbul** [comment]
@AkashYadavak please change filename as per guidelines, rn it is overwriting an existing file

**Comment by AkashYadavak** [comment]
Dear Shumbul,

I am really sorry for that. I am going to do that right now.

Thank you
Best regards
Akash Yadav

**Comment by AkashYadavak** [comment]
> @AkashYadavak please change filename as per guidelines, rn it is overwriting an existing file

I have done that.
Sorry for the delay.

**Review by shumbul — CHANGES_REQUESTED** [review]
Please check the 'Files' changes in your PR. It will delete some files if I approve. Please add those files in your PR or raise another one from a new branch.

**Pull request merged**
