### PR TITLE
14. Reverse a linked list- dhanwalkarjay.cpp

### PR DESCRIPTION
**Pull request by dhanwalkarjay**

### CODE REVIEW

**Review by shumbul — CHANGES_REQUESTED** [review]
Please check 'Files changed', existing file will get overwritten. 

Can you pls create a PR with file name '14. Reverse a linked list-dhanwalkarjay.cpp'?
image

image

**Comment by dhanwalkarjay** [comment]
Sorry, mam, for this. It's my first time sending a pull request to someone, so that's why I made these mistakes.

**Review by shumbul — APPROVED** [review]

**Comment by shumbul** [comment]
> Sorry, mam, for this. It's my first time sending a pull request to someone, so that's why I made these mistakes.

No worries at all! Hope you learnt something new!

**Comment by dhanwalkarjay** [comment]
Yes, I learned the pull request feature and how it works. Thank you, mam.

**Pull request merged**
